# Project & Channel Endpoints
# Select environment: View > Command Palette > "Rest Client: Switch Environment" -> local | dev

### List projects
GET {{baseUrl}}/projects
x-api-key: {{apiKey}}


### List projects including channel mappings
GET {{baseUrl}}/projects?include_channels=true
x-api-key: {{apiKey}}


### Get a single project (includes channel mappings)
GET {{baseUrl}}/projects/{{projectId}}
x-api-key: {{apiKey}}

### Register a project
# @name createProject
POST {{baseUrl}}/projects
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "name": "my-service",
  "repo_url": "https://github.com/rnettles/my-service",
  "default_branch": "main"
}


### Assign a Slack channel to a project
POST {{baseUrl}}/projects/{{projectId}}/channels
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "channel_id": "C12345678"
}
